# themes
include ~/.config/kitty/themes/Blazer.conf

# window maximum and minimum size
window_decorations normal

# fonts
font_family 0xProto Nerd Font
font_size 20

# background
background_opacity 100
